[package]
name = "subtp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
peg = "0.8.2"
regex = "1.10.3"
thiserror = "1.0.56"
